<?php $admin = $this->admin; ?>
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="view/skin/style.css">
</head>
<body>
<form action="<?php echo $this->getUrl('save'); ?>" method="post">
	<?php $this->setTemplate('html/header.phtml')->render();?>
	<br/>
	<br/>
	<table class="add-header">
		<tr align="center">
			<td><h2>ADMIN INFORMATION</h2></td>
		</tr>
	</table>
	<br/>
	<br/>
	<table class="add-data-table" align="center">
		<tr>
			<td>Name</td>
			<td><input type="text" name="admin[name]" value="<?php echo $admin->name; ?>"></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><input type="text" name="admin[email]" value="<?php echo $admin->email; ?>"></td>
		</tr>
		<tr>
			<td>Password</td>
			<td><input type="password" name="admin[password]" value="<?php echo $admin->password; ?>"></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="admin[status]">
					<?php foreach ($admin->getStatusOptions() as $key => $value) : ?>
					<?php $selected = ($key == $admin->getStatus()) ? "selected" : ''; ?>
					<option value="<?php echo $key; ?>" <?php echo $selected;?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>
		<tr>
			<td colspan="2"><button><a href="<?php echo $this->getUrl('grid', null, [], true); ?>">Cancel</a></button>
			<button type="submit">Submit</button></td>
		</tr>
	</table>
</form>
</body>
</html>