<?php
require_once 'Model/Product/Row.php';
$mediaRowObject = new Model_Product_Media_Row();
?>
<!DOCTYPE html>
<html>
<head>
	<title>Add Media</title>
	<link rel="stylesheet" type="text/css" href="view/skin/style.css">
</head>
<body>
	<form action="<?php echo $this->getUrlObject()->getUrl('save', null, ['id' => $_GET['product_id']], true);?>" method="post" enctype="multipart/form-data">
	<table class="add-header">
		<tr align="center">
			<td width="70%"><h2>ADD PRODUCT MEDIA</h2></td>
			<td><a href="<?php echo $this->getUrlObject()->getUrl('grid', null, ['id' => $_GET['product_id']], true);?>">Cancel</a></td>
			<td><button type="submit">Save</button></td>
		</tr>
	</table>
	<br/>
	<br/>

	<table class="add-data-table" align="center">
		<tr>
			<td>Name</td>
			<td>
				<input type="text" name="media[name]">
			</td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="product[status]">
					<option value="<?php echo Model_Product_Media::STATUS_ACTIVE; ?>"><?php echo Model_Product_Media::STATUS_ACTIVE_LBL; ?></option>
					<option value="<?php echo Model_Product_Media::STATUS_INACTIVE; ?>" selected><?php echo Model_Product_Media::STATUS_INACTIVE_LBL; ?></option>
					</select>
			</td>
		</tr>
		<tr>
			<td>Image</td>
			<td><input type="file" name="media[file]"></td>
		</tr>
		</table>
	</form>
</body>
</html>