<?php
require_once 'Model/Product/Row.php';
$mediaRowObject = new Model_Product_Media_Row();
?>
<!DOCTYPE html>
<html>
<head>
	<title>Add Media</title>
	<link rel="stylesheet" type="text/css" href="view/skin/style.css">
</head>
<body>
	<form action="<?php echo $this->getUrl('save', null, ['id' => $_GET['product_id']], true);?>" method="post" enctype="multipart/form-data">
		<table class="add-header">
			<tr>
				<td width="70%">Add Media</td>
				<td><a href="<?php echo $this->getUrl('grid', null, ['id' => $_GET['product_id']], true);?>">Cancel</a></td>
				<td><button type="submit">Save</button></td>
			</tr>
		</table>
		<br/>
		<br/>
		<table class="add-data-table" align="center">
			<tr>
				<td>Name</td>
				<td>
					<input type="text" name="media[name]">
				</td>
			</tr>
			<tr>
				<td>Status</td>
				<td>
					<select name="media[status]">
					<?php foreach ($mediaRowObject->getStatusOptions() as $key => $value) : ?>
					<option value="<?php echo $key; ?>"><?php echo $value; ?></option>
					<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td>Image</td>
				<td><input type="file" name="media[file]"></td>
			</tr>
		</table>
	</form>
</body>
</html>