<!DOCTYPE html>
<html>
<head>
	<title>Add Salesman</title>
	<link rel="stylesheet" type="text/css" href="view/skin/style.css">
</head>
<body>
<form action="<?php echo $this->getUrlObject()->getUrl('insert'); ?>" method="post">
	
	<table class="add-header">
		<tr>
			<td><h2>ADD SALESMAN</h2></td>
		</tr>
	</table>
	<br/>
	<br/>
			
	<table class="add-data-table" align="center">
		<tr>
			<td>First Name</td>
			<td><input type="text" name="salesman[first_name]"></td>
		</tr>
		<tr>
			<td>Last Name</td>
			<td><input type="text" name="salesman[last_name]"></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><input type="text" name="salesman[email]"></td>
		</tr>
		<tr>
			<td>Gender</td>
			<td>
				<select name="salesman[gender]">
					<option value="<?php echo Model_Product::GENDER_MALE; ?>"><?php echo Model_Product::GENDER_MALE_LBL; ?></option>
					<option value="<?php echo Model_Product::GENDER_FEMALE; ?>" selected><?php echo Model_Product::GENDER_FEMALE_LBL; ?></option>
				</select>
			</td>
		</tr>
		<tr>
			<td>Mobile</td>
			<td><input type="number" name="salesman[mobile]"></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="salesman[status]">
					<option value="<?php echo Model_Product::STATUS_ACTIVE; ?>"><?php echo Model_Product::STATUS_ACTIVE_LBL; ?></option>
					<option value="<?php echo Model_Product::STATUS_INACTIVE; ?>" selected><?php echo Model_Product::STATUS_INACTIVE_LBL; ?></option>
				</select>
			</td>
		</tr>
		<tr>
			<td>Company</td>
			<td><input type="number" name="salesman[company]"></td>
		</tr>
		<tr>
			<td colspan="2"><button><a href="<?php echo $this->getUrlObject()->getUrl('grid'); ?>">Cancel</a></button>
			<button type="submit">Submit</button></td>
		</tr>
	</table>
</form>
</body>
</html>