<?php
$products = $this->products; 
?>
<!DOCTYPE html>
<html>
<head>
	<title>Product</title>
	<link rel="stylesheet" type="text/css" href="view/skin/style.css">
</head>
<body>
	<table>
		<?php $this->setTemplate('html/header.phtml')->render();?>
		<?php $this->setTemplate('html/message.phtml')->render();?>
	</table>
	<br/>
	<br/>
	<table class="manage-table" border="1px">
		<tr align="center">
			<td width="70%">MANAGE PRODUCTS</td>
			<td><button><a href="<?php echo $this->getUrl('add', null , [], true);?>" style="text-decoration: none;">ADD PRODUCT</a></button></td>
		</tr>
	</table>
	<br/>
	<br/>
	<table class="grid-table" border="1px">
		<?php if (!$products): ?>
		<tr>
			<td colspan="8" align="center"><b>No data found.</b></td>
		</tr>
		<?php else: ?>
		<tr align="center">
			<th>Product Id</th>
			<th>Name</th>
			<th>SKU</th>
			<th>Cost</th>
			<th>Price</th>
			<th>Quantity</th>
			<th>Status</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>MEDIA</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach ($products as $product) : ?>
		<tr align="center">
			<td><?php echo $product->product_id; ?></td>
			<td><?php echo $product->name; ?></td>
			<td><?php echo $product->sku; ?></td>
			<td><?php echo $product->cost; ?></td>
			<td><?php echo $product->price; ?></td>
			<td><?php echo $product->quantity; ?></td>
			<td><?php echo $product->getStatusText(); ?></td>
			<td><?php echo $product->created_at; ?></td>
			<td><?php echo $product->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl(null, 'product_media', ['id'=> $product->product_id], true);?>">Media</a></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $product->product_id], true);?>">EDIT</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null, ['id'=> $product->product_id], true);?>">DELETE</a></td>
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</body>
</html>