<?php
$customers = $this->customers;
?>
<!DOCTYPE html>
<html>
<head>
	<title>Customer</title>
	<link rel="stylesheet" type="text/css" href="view/skin/style.css">
</head>
<body>
	<table>
		<?php $this->setTemplate('html/header.phtml')->render();?>
		<?php $this->setTemplate('html/message.phtml')->render();?>
	</table>
	<br/>
	<br/>
	<table class="manage-table" border="1px">
		<tr align="center">
			<td width="70%">MANAGE CUSTOMER</td>
			<td><button><a href="<?php echo $this->getUrl('add', null , [], true);?>" style="text-decoration: none;">ADD CUSTOMER</a></button></td>
		</tr>
	</table>
	<br/>
	<br/>
	<table class="grid-table" border="1px">
		<?php if (!$customers): ?>
		<tr>
			<td colspan="8" align="center"><b>No data found.</b></td>
		</tr>
		<?php else: ?>
		<tr align="center">
			<th>Customer Id</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Gender</th>
			<th>Mobile</th>
			<th>Status</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach ($customers as $customer) : ?>
		<tr align="center">
			<td><?php echo $customer->customer_id; ?></td>
			<td><?php echo $customer->first_name; ?></td>
			<td><?php echo $customer->last_name; ?></td>
			<td><?php echo $customer->email; ?></td>
			<td><?php echo $customer->gender; ?></td>
			<td><?php echo $customer->mobile; ?></td>
			<td><?php echo $customer->getStatusText(); ?></td>
			<td><?php echo $customer->created_at; ?></td>
			<td><?php echo $customer->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $customer->customer_id], true);?>">EDIT</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null , ['id'=> $customer->customer_id], true);?>">DELETE</a></td>
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</body>
</html>